version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: trackmovie
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - ./data:/var/lib/postgresql/data